### ISSUE TITLE
"Streaming cable" PiP capability documentation missing

### ISSUE THREAD

**Issue by zbeekman** [LattePandaTeam/Docs-for-MKII#1]
Hi I am considering buying the Alpha. However, my use case would be a portable windows development rig that is more responsive than running inside of VirtualBox.

Can you please document how to use the "streaming cable" to control and display Windows 10 on LattePanda Alpha from a macOS laptop?

There is no information on the internet about how to do this, however, all of your marketing materials prominently feature this functionality. Does it actually work? How do you set it up?

From https://www.dfrobot.com/product-1729.html:

> The Streaming Cable enables your Windows-enabled LattePanda device to act like a USB on a Mac or Linux system. Just plug & play into your Apple/Linux device! The PiP (Picture in Picture) form also eliminates the switching/use of dual mouse and HDMI to connect different systems for seamless interaction of two different systems.

**Comment by LattePanda** [comment]
Yes. Thanks for your comments! Now we are still working our the production for the streaming cable. When everything is ready, we will start to release the docs for what you mentioned! 

The classic scenarios of Streaming cable is just what you are talking about. We are Mac laptop user and we create streaming cable for developer to build cross platform environment quickly with smoothly  development experience. That's the purpose!

**Comment by LattePanda** [comment]
So please be patient and keep an eye on www.lattepanda.com
Thanks!

**Comment by zbeekman** [comment]
Great, thanks for the update.
